# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        ":categories/:title/"
baseurl:          /git
relative_permalinks: true

# Setup
title:            'Git y Github'
tagline:          'Curso introductorio'
description:      'Fundamentos de colaboración y control de versiones distribuidas'
url:              http://rizomas.org/git

author:
  name:           'Luis Borjas'
  url:            http://rizomas.org

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/rizoma/git
